// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Entity;

namespace server.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20201118023516_AddColumnToTable_CaThi_IdGiamThi")]
    partial class AddColumnToTable_CaThi_IdGiamThi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Entity.CaThi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IdGiamThi")
                        .HasColumnType("bigint");

                    b.Property<long>("IdHocPhan")
                        .HasColumnType("bigint");

                    b.Property<long>("IdLopHoc")
                        .HasColumnType("bigint");

                    b.Property<string>("TenCaThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ThoiGianBatDau")
                        .HasColumnType("bigint");

                    b.Property<long>("ThoiGianThi")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdGiamThi");

                    b.HasIndex("IdHocPhan");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("CaThi");
                });

            modelBuilder.Entity("Server.Entity.CauHoi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DoKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdKhoCauHoi")
                        .HasColumnType("bigint");

                    b.Property<bool>("NhieuDapAn")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhoCauHoi");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("Server.Entity.ChiTietDeThi", b =>
                {
                    b.Property<long>("IdDeThi")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCauHoi")
                        .HasColumnType("bigint");

                    b.HasKey("IdDeThi", "IdCauHoi");

                    b.HasIndex("IdCauHoi");

                    b.ToTable("ChiTietDeThi");
                });

            modelBuilder.Entity("Server.Entity.DapAn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DapAnDung")
                        .HasColumnType("bit");

                    b.Property<long>("IdCauHoi")
                        .HasColumnType("bigint");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCauHoi");

                    b.ToTable("DapAn");
                });

            modelBuilder.Entity("Server.Entity.DeThi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DeThiThu")
                        .HasColumnType("bit");

                    b.Property<long>("IdHocPhan")
                        .HasColumnType("bigint");

                    b.Property<bool>("SanSang")
                        .HasColumnType("bit");

                    b.Property<string>("TenDeThi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdHocPhan");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("Server.Entity.HocPhan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenHocPhan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HocPhan");
                });

            modelBuilder.Entity("Server.Entity.KhoCauHoi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IdHocPhan")
                        .HasColumnType("bigint");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoCauHoi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdHocPhan");

                    b.ToTable("KhoCauHoi");
                });

            modelBuilder.Entity("Server.Entity.LopHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("Server.Entity.SinhVien", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdLopHoc")
                        .HasColumnType("bigint");

                    b.Property<string>("MSSV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("Server.Entity.TaiKhoan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenTruyCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Server.Entity.CaThi", b =>
                {
                    b.HasOne("Server.Entity.TaiKhoan", "GiamThi")
                        .WithMany("DsCaThi")
                        .HasForeignKey("IdGiamThi")
                        .HasConstraintName("FK_GiamThi_CaThi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Entity.HocPhan", "HocPhan")
                        .WithMany("DsCaThi")
                        .HasForeignKey("IdHocPhan")
                        .HasConstraintName("FK_HocPhan_CaThi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Entity.LopHoc", "LopHoc")
                        .WithMany("DsCaThi")
                        .HasForeignKey("IdLopHoc")
                        .HasConstraintName("FK_LopHoc_CaThi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entity.CauHoi", b =>
                {
                    b.HasOne("Server.Entity.KhoCauHoi", "KhoCauHoi")
                        .WithMany("DsCauHoi")
                        .HasForeignKey("IdKhoCauHoi")
                        .HasConstraintName("FK_KhoCauHoi_CauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entity.ChiTietDeThi", b =>
                {
                    b.HasOne("Server.Entity.CauHoi", "CauHoi")
                        .WithMany("DsDeThi")
                        .HasForeignKey("IdCauHoi")
                        .HasConstraintName("FK_CauHoi_ChiTietDeThi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Entity.DeThi", "DeThi")
                        .WithMany("DsCauHoi")
                        .HasForeignKey("IdDeThi")
                        .HasConstraintName("FK_DeThi_ChiTietDeThi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entity.DapAn", b =>
                {
                    b.HasOne("Server.Entity.CauHoi", "CauHoi")
                        .WithMany("DsDapAn")
                        .HasForeignKey("IdCauHoi")
                        .HasConstraintName("FK_CauHoi_DapAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entity.DeThi", b =>
                {
                    b.HasOne("Server.Entity.HocPhan", "HocPhan")
                        .WithMany("DsDeThi")
                        .HasForeignKey("IdHocPhan")
                        .HasConstraintName("FK_HocPhan_DeThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entity.KhoCauHoi", b =>
                {
                    b.HasOne("Server.Entity.HocPhan", "HocPhan")
                        .WithMany("DsKhoCauHoi")
                        .HasForeignKey("IdHocPhan")
                        .HasConstraintName("FK_HocPhan_KhoCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entity.SinhVien", b =>
                {
                    b.HasOne("Server.Entity.LopHoc", "LopHoc")
                        .WithMany("DsSinhVien")
                        .HasForeignKey("IdLopHoc")
                        .HasConstraintName("FK_LopHoc_SinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
