// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Entity;

namespace server.Migrations
{
  [DbContext(typeof(ServerContext))]
  [Migration("20201029182401_AddTable_TaiKhoan")]
  partial class AddTable_TaiKhoan
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.1.9")
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("Server.Entity.TaiKhoan", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint")
                      .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<string>("Email")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("GioiTinh")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("HoTen")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("MatKhau")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("SoDienThoai")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Username")
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("TaiKhoan");
          });
#pragma warning restore 612, 618
    }
  }
}
